options:
  kcql:
    type: string
    default: ""
    description: "KCQL statement. Syntax at https://lenses.stream/2.0/connectors/sink/influx.html#kcql-support."
  database:
    type: string
    default: ""
    description: "Name of the InfluxDB database to be created/used."
  max-tasks:
    type: int
    default: 5
    description: |
      Max number of tasks.

